### PR TITLE
Added a new plant

### PR DESCRIPTION
**Pull request by HelgeGH**
I added a new plant based on Henry and Youmu. After placing it, it slashes every zombie on the map a few times, dealing a lot of damage, before disappearing afterwards.

I also tried to add some animations to it by changing its sprite every few frames. This also applies to the sword slashes it makes.

### CODE REVIEW

**Comment by mxbi** [comment]
Thanks for the PR! 😄 

The youmusprite files are supposedly 1200x1200, but they look like they've been agressively upscaled from something way smaller:
image

Do we have either higher res versions or the original resolution versions of these? (There's no point containing an upscaled version with the game when it hasn't got any extra quality over a smaller one that would just be upscaled on the fly if needed)

**Comment by HelgeGH** [comment]
RPYoumuS2_12
I took the images from this gif, so the quality is pretty bad, but I have the original images, so I can create new .png-files with a lower resolution. 

Also, since the sword is pointing upwards in one of the frames, I had to make the sprite smaller to get everything to fit into the frame. Therefore, the sprite looks really small.

We should also probably change the sprite for something else with a higher quality in the future.

**Comment by mxbi** [comment]
Then yeah, at the moment I would make it so the sprites we're using are the original resolution and not upscaled. I think the lanczos (or whatever upscaling filter was used) doesn't look too great on pixel art like the gif so it's best to avoid that.

> Also, since the sword is pointing upwards in one of the frames, I had to make the sprite smaller to get everything to fit into the frame. Therefore, the sprite looks really small.

Ahh, that explains why there's so much empty space at the top of the sprite. That sounds good then :)

**Comment by HelgeGH** [comment]
Ok, I can fix that.

**Comment by mxbi** [comment]
Thanks a lot @HelgeGH! Merging

**Pull request merged**
